# Generated by Django 5.2.1 on 2025-05-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='ID чата в телеграмме', unique=True, verbose_name='ID чата')),
                ('first_name', models.CharField(help_text='Имя пользователя в телеграмме', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия пользователя в телеграмме', max_length=255, verbose_name='Фамилия')),
                ('username', models.CharField(help_text='Имя пользователя в телеграмме', max_length=255, verbose_name='Имя пользователя')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата регистрации пользователя', verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название объекта', max_length=255, verbose_name='Название объекта')),
                ('category', models.ForeignKey(help_text='Категория', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='telegramBot.category', verbose_name='Категория')),
            ],
        ),
    ]
